# 모델 평가

In [1]:
import pandas as pd

data = pd.read_csv('../data/Fvote.csv')
data.head()

edu  income  age  score_gov  score_progress  score_intention  vote  \
0    3       3    3          2               2              4.0     1   
1    2       3    3          2               4              3.0     0   
2    1       2    4          1               3              2.8     1   
3    2       1    3          5               4              2.6     1   
4    1       2    4          4               3              2.4     1   

   parties  gender_female  gender_male  region_Chungcheung  region_Honam  \
0        2              0            1                   0             0   
1        3              0            1                   0             0   
2        4              0            1                   0             1   
3        1              1            0                   0             0   
4        1              0            1                   0             0   

   region_Others  region_Sudo  region_Youngnam  
0              0            0                1  
1              1            0                0  
2              0            0                0  
3              0            1                0  
4              0            1                0

In [2]:
X = data.loc[:, ~data.columns.isin(['vote', 'parties'])]  # df.columns.isin([])하면 해당 컬럼만 가져오고 ~해서 부정함 
X

edu  income  age  score_gov  score_progress  score_intention  \
0      3       3    3          2               2              4.0   
1      2       3    3          2               4              3.0   
2      1       2    4          1               3              2.8   
3      2       1    3          5               4              2.6   
4      1       2    4          4               3              2.4   
..   ...     ...  ...        ...             ...              ...   
206    1       4    4          3               3              1.8   
207    2       1    2          3               4              2.6   
208    2       1    2          3               3              2.6   
209    2       3    4          3               2              4.0   
210    2       2    2          3               3              3.8   

     gender_female  gender_male  region_Chungcheung  region_Honam  \
0                0            1                   0             0   
1                0            1                   0             0   
2                0            1                   0             1   
3                1            0                   0             0   
4                0            1                   0             0   
..             ...          ...                 ...           ...   
206              0            1                   0             0   
207              0            1                   0             0   
208              0            1                   1             0   
209              0            1                   0             0   
210              1            0                   0             0   

     region_Others  region_Sudo  region_Youngnam  
0                0            0                1  
1                1            0                0  
2                0            0                0  
3                0            1                0  
4                0            1                0  
..             ...          ...              ...  
206              0            0                1  
207              0            1                0  
208              0            0                0  
209              0            1                0  
210              0            1                0  

[211 rows x 13 columns]

In [3]:
y = data[['vote']]
y

vote
0       1
1       0
2       1
3       1
4       1
..    ...
206     1
207     1
208     1
209     1
210     1

[211 rows x 1 columns]

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

## 모델에 하이퍼 파라미터 명시

In [6]:
from sklearn.linear_model import LogisticRegression

In [8]:
model = LogisticRegression(C=10)
model.fit(X_train, y_train.values.ravel())

LogisticRegression(C=10)

In [9]:
model.predict(X_train)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1])

In [10]:
model.score(X_train, y_train)

0.740506329113924

In [11]:
model.predict(X_test)

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1])

In [13]:
model.score(X_test, y_test)

0.6792452830188679

# 다중 분류(parties)

In [15]:
y = data[['parties']]  # parties는 1,2,3,4중 하나임

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
model = LogisticRegression(C=10)
model.fit(X_train, y_train.values.ravel())

/usr/local/Caskroom/miniforge/base/envs/condaTest/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=10)

In [19]:
model.score(X_train, y_train)

0.6329113924050633

In [24]:
import numpy as np

In [26]:
np.round_(model.predict_proba(X_test), 3)

array([[0.134, 0.412, 0.267, 0.187],
       [0.1  , 0.266, 0.295, 0.339],
       [0.43 , 0.027, 0.002, 0.542],
       [0.036, 0.577, 0.065, 0.321],
       [0.05 , 0.303, 0.01 , 0.637],
       [0.067, 0.091, 0.161, 0.681],
       [0.087, 0.386, 0.226, 0.302],
       [0.601, 0.073, 0.077, 0.249],
       [0.043, 0.232, 0.105, 0.621],
       [0.278, 0.114, 0.197, 0.412],
       [0.322, 0.294, 0.014, 0.369],
       [0.02 , 0.735, 0.018, 0.228],
       [0.142, 0.241, 0.034, 0.583],
       [0.024, 0.088, 0.061, 0.827],
       [0.78 , 0.005, 0.019, 0.196],
       [0.079, 0.452, 0.174, 0.295],
       [0.964, 0.   , 0.022, 0.013],
       [0.025, 0.43 , 0.237, 0.307],
       [0.196, 0.354, 0.05 , 0.399],
       [0.106, 0.418, 0.186, 0.29 ],
       [0.099, 0.368, 0.292, 0.241],
       [0.152, 0.025, 0.049, 0.774],
       [0.005, 0.544, 0.053, 0.398],
       [0.712, 0.05 , 0.126, 0.112],
       [0.013, 0.789, 0.013, 0.185],
       [0.52 , 0.006, 0.316, 0.159],
       [0.495, 0.016, 0.2  , 0.289],
 